"""ForgeBot — render and post Resilience Reports as GitHub PR comments."""

from __future__ import annotations


def render_pr_comment(report: dict) -> str:
    """
    Render a Resilience Report as a GitHub-flavored Markdown PR comment.

    Args:
        report: Resilience Report dict (from build_report / load_report)

    Returns:
        Markdown string suitable for posting as a GitHub PR comment
    """
    ars = report.get("ars_score", 0.0)
    run_id = report.get("run_id", "unknown")
    attack_count = report.get("attack_count", 0)
    mitigated = report.get("mitigated_count", 0)
    missed = report.get("miss_count", 0)
    elapsed = report.get("elapsed_seconds", 0)
    pass_threshold = report.get("pass_threshold", 0.80)

    passed = ars >= pass_threshold
    gate_emoji = "✅" if passed else "❌"
    gate_label = "PASSED" if passed else "BLOCKED"

    ars_bar = _ars_bar(ars)

    lines = [
        f"## {gate_emoji} GAUNTLEX Adversarial Resilience Report — `{run_id}`",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| **ARS Score** | `{ars:.3f}` {ars_bar} |",
        f"| **Gate** | **{gate_label}** (threshold: {pass_threshold:.2f}) |",
        f"| Attacks fired | {attack_count} |",
        f"| Mitigated | {mitigated} |",
        f"| Missed | {missed} |",
        f"| Elapsed | {elapsed}s |",
        "",
    ]

    attacks = report.get("attacks", [])
    missed_attacks = [a for a in attacks if a.get("verdict") == "MISSED"]
    if missed_attacks:
        lines.append("### ⚠ Unmitigated Attacks")
        lines.append("")
        for atk in missed_attacks[:5]:
            cwe = atk.get("cwe", "")
            title = atk.get("title", "")
            sev = atk.get("severity", "medium").upper()
            lines.append(f"- **[{cwe}]** {title} `{sev}`")
        if len(missed_attacks) > 5:
            lines.append(f"- _(+{len(missed_attacks) - 5} more — see full report)_")
        lines.append("")

    control_mappings = report.get("control_mappings", {})
    if control_mappings:
        lines.append("### Compliance Control Mappings")
        lines.append("")
        for framework, controls in list(control_mappings.items())[:3]:
            ctrl_list = ", ".join(f"`{c}`" for c in (controls or [])[:4])
            lines.append(f"- **{framework}**: {ctrl_list}")
        lines.append("")

    hash_val = report.get("integrity_hash", "")
    if hash_val:
        lines.append(f"<sub>SHA-256 integrity: `{hash_val[:16]}…` · Verify: `gauntlex verify {run_id}`</sub>")
        lines.append("")

    lines.append("---")
    lines.append("<sub>Generated by [GAUNTLEX](https://github.com/sanjoy1234/gauntlex) — Adversarial Co-Generation Engine</sub>")

    return "\n".join(lines)


def _ars_bar(ars: float, width: int = 10) -> str:
    """Return a Unicode progress bar for the ARS score."""
    filled = int(ars * width)
    bar = "█" * filled + "░" * (width - filled)
    return f"`{bar}`"


async def post_comment(
    owner: str,
    repo: str,
    pr_number: int,
    report: dict,
    token: str | None = None,
) -> bool:
    """
    Post the Resilience Report as a GitHub PR comment.

    Args:
        owner: GitHub org or user
        repo: Repository name
        pr_number: PR number
        report: Resilience Report dict
        token: GitHub token (falls back to GITHUB_TOKEN env var)

    Returns:
        True if comment was posted successfully
    """
    import os
    import httpx

    token = token or os.environ.get("GITHUB_TOKEN", "")
    if not token:
        return False

    body = render_pr_comment(report)
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(
                url,
                json={"body": body},
                headers={
                    "Authorization": f"token {token}",
                    "Accept": "application/vnd.github.v3+json",
                },
            )
            return resp.status_code in (200, 201)
    except Exception:
        return False
